---

- name: Monitoring - Prometheus | Create compose directory
  file:
    path: "{{ prometheus_compose_files_path }}"
    state: directory
    recurse: yes

- name: Monitoring - Prometheus | Create persistance nad configuration folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_configuration_path }}"
    - "{{ prometheus_persistence_path }}"

- name: Monitoring - Prometheus | Create persistance nad configuration folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "nobody"
    group: "nogroup"
  with_items:
    - "{{ prometheus_configuration_path }}"
    - "{{ prometheus_persistence_path }}"

- name: Monitoring - Prometheus | Copy docker compose file
  template:
    src: docker-compose.prometheus.yml.j2
    dest: "{{ prometheus_compose_files_path }}/docker-compose.prometheus.yml"

- name: Monitoring - Prometheus | Template configuration file prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_configuration_path }}/prometheus.yml"
    owner: nobody
    group: nogroup
    mode: '0644'
  when: prometheus_custom_config_enabled

- name: Monitoring - Prometheus | Run container
  docker_compose:
    project_name: prometheus
    project_src: "{{ prometheus_compose_files_path }}"
    files:
      - docker-compose.prometheus.yml
