---

- name: Monitoring - Prometheus | Ensure group "{{ prometheus_group }}" exists
  group:
    name: "{{ prometheus_group }}"
    state: present
    gid: "{{ prometheus_gid }}"

- name: Monitoring - Prometheus | Ensure user "{{ prometheus_user }}" exists
  user:
    name: "{{ prometheus_user }}"
    shell: /bin/nologin
    state: present
    group: "{{ prometheus_group }}"
    uid: "{{ prometheus_uid }}"

- name: Monitoring - Prometheus | Create compose directory
  file:
    path: "{{ prometheus_compose_files_path }}"
    state: directory
    recurse: yes

- name: Monitoring - Prometheus | Create persistance and configuration folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_configuration_path }}"
    - "{{ prometheus_persistence_path }}"

- name: Monitoring - Prometheus | Change owner and group of persistance and configuration folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "nobody"
    group: "nogroup"
  with_items:
    - "{{ prometheus_configuration_path }}"
    - "{{ prometheus_persistence_path }}"

- name: Monitoring - Prometheus | Copy docker compose file
  template:
    src: docker-compose.prometheus.yml.j2
    dest: "{{ prometheus_compose_files_path }}/docker-compose.prometheus.yml"

- name: Monitoring - Prometheus | Template configuration file prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_configuration_path }}/prometheus.yml"
    owner: nobody
    group: nogroup
    mode: '0644'
  when: prometheus_custom_config_enabled

- name: Monitoring - Prometheus | Run container
  docker_compose:
    project_name: prometheus
    project_src: "{{ prometheus_compose_files_path }}"
    files:
      - docker-compose.prometheus.yml
